### ISSUE TITLE
undefined method loadProductCount

### ISSUE THREAD

**Issue by webmastermicromaint** [fballiano/magento-hide-empty-categories#11]
PHP Fatal error:  Call to undefined method Mage_Catalog_Model_Resource_Category_Flat_Collection::loadProductCount() in /app/code/community/Fballiano/HideEmptyCategories/Model/Observer.php on line 41

Error comes only sometime... 
Maybe while reindexing.
---------------------------------
Magento ver. 1.9.1.0
Category flat enabled.

**Comment by fballiano** [comment]
sorry, I can test it on 1.9.1 but I can't reproduce it on 1.9.4
