### ISSUE TITLE
Fatal error: Call to a member function isBuilt() on a non-object in

### ISSUE THREAD

**Issue by mufaddal-aydus** [fballiano/magento-hide-empty-categories#5]
Fatal error: Call to a member function isBuilt() on a non-object in app\code\core\Mage\Catalog\Helper\Category\Flat.php on line 80 with flat catalog enabled

**Comment by fballiano** [comment]
which version of magento are you using?
i'm not getting this error on 1.8 and 1.9 with flat enabled.

**Comment by fballiano** [comment]
closed for no feedback
