### ISSUE TITLE
loadProductCount() error!

### ISSUE THREAD

**Issue by MaurizioBrioschi** [fballiano/magento-hide-empty-categories#6]
I got an error with this function....
Without it everything seems to be ok

```
Fatal error: Call to undefined method Mage_Catalog_Model_Resource_Category_Flat_Collection::loadProductCount() in /srv/waketoolz.vm/www/.modman/magento-hide-empty-categories/app/code/community/Fballiano/HideEmptyCategories/Model/Observer.php on line 41
```

**Comment by fballiano** [comment]
did you try 0.3?
which magento version are you on?
do you use flat catalog?

**Comment by MaurizioBrioschi** [comment]
yes, i have fork the repo just 10 minutes ago, so i'm working on the master branch
i'm working with version 1.9.1 and of course flat catalog

**Comment by fballiano** [comment]
i'm on 1.9.2 but...
dunno, i'll try to reproduce it

**Comment by MaurizioBrioschi** [comment]
In any case i think that is better to find a work around to this method that is not always available... probably is better to check if the category is an anchor category before use it

**Comment by fballiano** [comment]
if you replace the observer with this code:

```php
<?php
class Fballiano_HideEmptyCategories_Model_Observer
{
    public function catalogCategoryFlatLoadnodesBefore(Varien_Event_Observer $observer)
    {
        $select = $observer->getEvent()->getSelect();
        $select->columns("display_mode");
    }

    public function catalogCategoryCollectionLoadBefore(Varien_Event_Observer $observer)
    {
        $collection = $observer->getEvent()->getCategoryCollection();
        $collection->addAttributeToSelect("display_mode");
        $collection->addAttributeToSelect("is_anchor");
    }

    public function catalogCategoryCollectionLoadAfter(Varien_Event_Observer $observer)
    {
        $collection = $observer->getEvent()->getCategoryCollection();
        if (!method_exists($collection, "loadProductCount")) return;

        $collection->loadProductCount($collection->getItems(), true, true);
        foreach ($collection as $key => $item) {
            if ($item->getEntityTypeId() == 3) {
                if ($item->getDisplayMode() == "PAGE") continue;
                if ($item->getProductCount()) continue;
                $collection->removeItemByKey($key);
            }
        }
    }
}
```

does it work or simply does not output the error?

**Comment by MaurizioBrioschi** [comment]
Basically if you exit if the method doesn't exist you are not able to remove items

**Comment by fballiano** [comment]
i did that modification cause you said "if you remove that line it works" but i thought the "removing" process was not happening in that function but in some other observer's method.

can you send me a stripped down dump of your core_config_data table? I'm unable to reproduce the error

**Comment by fballiano** [comment]
is yours a vanilla magento installation or you have some modules who can set themselves in the middle?

**Comment by fballiano** [comment]
closed, no feedback

**Comment by manojchowrasiya** [comment]
Is this work on multi website environment with same category tree,it is not working at my end.
