### ISSUE TITLE
After installion site going blank

### ISSUE THREAD

**Issue by rajatcompubrain** [fballiano/magento-hide-empty-categories#8]
Hi Fballiano,
I want to hide some categories from menu and extension work as required me.
But after some time whole site showing blank page remain only menu.
Please help me to find out the solution.
Thanks in advance.

**Comment by fballiano** [comment]
what magento version are you running?

**Comment by rajatcompubrain** [comment]
Magento ver. 1.9.2.2

**Comment by rajatcompubrain** [comment]
Hi Fballiano,
Please help me to solve it.

**Comment by fballiano** [comment]
can you clean the cache?
can you try at least to disable/uninstall the module?

**Comment by rajatcompubrain** [comment]
Currently i have uninstalled the extension from my store.

**Comment by pabloblazquez** [comment]
How can I disable/uninstall your module?

**Comment by fballiano** [comment]
if you remove the files or even just the xml in app/etc/modules the module it's gone... there's nothing else to do.
