### ISSUE TITLE
Module working Great with Main Menu, but not OK with Side Menu

### ISSUE THREAD

**Issue by Mishef** [fballiano/magento-hide-empty-categories#9]
Hello and thank you for this module!

I have only one problem - Module do not work with Side Menu in website.

You can see example here: http://i.imgur.com/HhHJl5G.jpg

Can you help me with this issue?

Greetings,
Atanas Mishev
Magento ver 1.9.2.1

**Comment by fballiano** [comment]
it's working for me

![Schermata 2019-04-23 alle 12 50 45](https://user-images.githubusercontent.com/909743/56578813-7311ff00-65c6-11e9-9322-9f5f5d3c83fe.jpg)

it's not easy to understand my screenshot but there should be a cat.1.2 category which is hidden in both menus.

tested with flat enabled and disabled

can it be a matter of cache/indexing?
